openapi: 3.0.0
info:
  title: 'phpMyFAQ REST API'
  contact:
    name: 'phpMyFAQ Team'
    email: support@phpmyfaq.de
  license:
    name: 'Mozilla Public Licence 2.0'
    url: 'https://www.mozilla.org/MPL/2.0/'
  version: '3.0'
servers:
  - url: 'https://localhost'
    description: 'Local dockerized server'
paths:
  /api/v3.0/open-questions:
    get:
      operationId: getOpenQuestions
      responses:
        '200':
          description: 'Returns the open questions for the given language provided by "Accept-Language".'
          headers:
            Accept-Language:
              description: 'The language code for the open questions.'
              schema:
                type: string
          content:
            application/json:
              schema: {}
              example: "\n        [\n            {\n                \"id\": 1,\n                \"lang\": \"en\",\n                \"username\": \"phpMyFAQ User\",\n                \"email\": \"user@example.org\",\n                \"categoryId\": 3,\n                \"question\": \"Foo? Bar? Baz?\",\n                \"created\": \"20190106180429\",\n                \"answerId\": 0,\n                \"isVisible\": \"N\"\n              }\n        ]"
        '404':
          description: 'If no open questions are stored.'
          headers:
            Accept-Language:
              description: 'The language code for the open questions.'
              schema:
                type: string
          content:
            application/json:
              schema: {}
              example: []
  /api/v3.0/search:
    get:
      operationId: getSearch
      parameters:
        - name: q
          in: query
          description: 'The search term'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Returns the results for the query string search term.'
          content:
            application/json:
              schema: {}
              example: "\n        [\n            {\n                \"id\": \"1\",\n                \"lang\": \"en\",\n                \"category_id\": \"15\",\n                \"question\": \"Why are you using phpMyFAQ?\",\n                \"answer\": \"Because it is cool!\",\n                \"link\": \"https://www.example.org/index.php?action=faq&cat=15&id=1&artlang=en\"\n            }\n        ]"
        '404':
          description: 'If the search returns no results'
          content:
            application/json:
              schema: {}
              example: []
  /api/v3.0/tags:
    get:
      operationId: getTags
      responses:
        '200':
          description: 'Returns the tags for the given language provided by "Accept-Language".'
          content:
            application/json:
              schema: {}
              example: "[\n            {\"tagId\": 4, \"tagName\": \"phpMyFAQ\", \"tagFrequency\": 3 },\n            {\"tagId\": 1, \"tagName\": \"PHP 8\", \"tagFrequency\": 2 }\n        ]"
        '404':
          description: 'If no tags are stored.'
          content:
            application/json:
              schema: {}
              example: []
  /api/v3.0/title:
    get:
      operationId: getTitle
      responses:
        '200':
          description: 'Returns the title of the phpMyFAQ instance as a string.'
          content:
            application/json:
              schema: {}
              example: 'phpMyFAQ Codename Pontus'
  /api/v3.0/version:
    get:
      operationId: getVersion
      responses:
        '200':
          description: 'Returns the phpMyFAQ version number as string.'
          content:
            application/json:
              schema: {}
              example: 4.0.0
